spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate
    username: hibernate
    password: hibernate
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true